### ISSUE TITLE
Dust/Hour goes negative after banking

### ISSUE THREAD

**Issue by kirklandfruits** [kevindarbydev/stardust-per-hour-calculator#1]
title
Turning the plugin off and on again doesn't reset, either.

**Comment by kevindarbydev** [comment]
> title Turning the plugin off and on again doesn't reset, either.

I've just pushed a change that should fix that, may take a couple days before it's merged into the official runelite plugin hub.

Thanks for pointing that out!

**Comment by kirklandfruits** [comment]
Excellent wizardry, thank you for your expertise!
